### ISSUE TITLE
У меня этот скрипт работает некорректно

### ISSUE THREAD

**Issue by uilim-test** [CryptoManiac/node-solo-proxy#1]
У меня этот скрипт работает некорректно.

Эффективность очень низкая.

Через какое-то время после подключения асика в логах появляется ошибка:
Fatal Error: network connection lost![2]
Асик теряет связь с сетью. Соответственно сразу пропадает хешрейт, через какое-то время поднимается до актуального уровня, а потом опять та же самая ошибка.
С интернетом и сетью всё в порядке, проверял.
Пробовал ставить скрипт на VDS сервер - та же ошибка.
Пробовал оперировать с настройками diff - не помогает.
Настройки демона монеты пробовал разные, ничего не помогает.
java node 12. Пробовал разные версии.
Подскажите, может что-то где-то нужно ещё насторить?

**Comment by CryptoManiac** [comment]
Приветствую. Вероятно, падает сервер где-то на необработанном исключении, надо смотреть.
Вообще, скрипт демонстрационный, для облегчения понимания смысла процесса, как таковой цели сделать стабильный стратум сервер не было. Вероятно, будет выброшено и переписано заново.
